inputs:
  environment:
    type: environment
    required: true

runs:
  using: composite
  environment: ${{ inputs.environment }}
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tag and push images to stage and prod ACR
      shell: bash
      run: |
        docker pull niklassparfeldgcx/release-demo:${{ github.sha }}
        docker tag niklassparfeldgcx/release-demo:${{ github.sha }} niklassparfeldgcx/release-demo:${{ inputs.environment }}-${{ github.sha }}
        docker push niklassparfeldgcx/release-demo:${{ inputs.environment }}-${{ github.sha }}
