name: "CD"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: niklassparfeldgcx/release-demo:${{ github.sha }}
  release:
    uses: ./.github/workflows/release-to-env.yaml
    needs: build
    with:
      environment: development
      gitref: ${{ github.sha }}
    secrets: inherit
