name: "deploy / development"

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/subflow-build-and-push.yaml
    secrets: inherit
  release:
    uses: ./.github/workflows/subflow-release-to-env.yaml
    needs: build
    secrets: inherit
    with:
      environment: development
      gitref: ${{ github.sha }}
