name: "CD"

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/flows/build-and-push.yaml
    secrets: inherit
  release:
    uses: ./.github/workflows/flows/release-to-env.yaml
    needs: build
    secrets: inherit
    with:
      environment: development
      gitref: ${{ github.sha }}
