name: "cd / development"

on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/subflow-build-and-push.yaml
    secrets: inherit
  deploy:
    uses: ./.github/workflows/subflow-deploy-to-env.yaml
    needs: build
    secrets: inherit
    with:
      environment: development
