name: "deploy / production"

on:
  release:
    types: [published, released]

jobs:
  release:
    if: github.event_name == 'release'
    uses: ./.github/workflows/subflow-release-to-env.yaml
    secrets: inherit
    with:
      environment: production
      gitref: ${{ github.sha }}
