name: "CD"

on:
  release:
    types: [published]

jobs:
  release:
    if: github.event_name == 'release'
    uses: ./.github/workflows/subflow-release-to-env.yaml
    needs: build
    secrets: inherit
    with:
      environment: production
      gitref: ${{ github.sha }}
