name: "deploy / staging"

on:
  release:
    types: [published, prereleased]

jobs:
  release:
    if: github.event_name == 'pre-release'
    uses: ./.github/workflows/subflow-release-to-env.yaml
    secrets: inherit
    with:
      environment: staging
      gitref: ${{ github.sha }}
