name: "deploy / staging"

on:
  release:
    types: [published]

jobs:
  release:
    if: "github.event.release.prerelease"
    uses: ./.github/workflows/subflow-release-to-env.yaml
    secrets: inherit
    with:
      environment: staging
      gitref: ${{ github.sha }}
