name: "deploy / staging"

on:
  release:
    types: [published]

jobs:
  deploy:
    if: "github.event.release.prerelease"
    uses: ./.github/workflows/subflow-deploy-to-env.yaml
    secrets: inherit
    with:
      environment: staging
