name: "Release"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to release into"
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release
