name: "Release"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to release into"
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - shell: bash
        run: |
          docker pull niklassparfeldgcx/release-demo:${{ github.sha }}
          docker tag niklassparfeldgcx/release-demo:${{ github.sha }} niklassparfeldgcx/release-demo:${{ inputs.environment }}-${{ github.sha }}
          docker push niklassparfeldgcx/release-demo:${{ inputs.environment }}-${{ github.sha }}
